# Generated by Django 2.2.6 on 2019-11-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField(default=0)),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('color', models.TextField()),
                ('VIN', models.TextField()),
                ('production_date', models.DateField()),
                ('engine_capacity', models.IntegerField()),
                ('fuel_type', models.TextField()),
                ('mileage', models.IntegerField()),
                ('OC_date', models.DateField(blank=True, default='1970-01-01')),
                ('car_review_date', models.DateField(blank=True, default='1970-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.TextField()),
                ('userID', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_accepted', models.BooleanField()),
                ('is_finished', models.BooleanField()),
                ('total_prize', models.FloatField()),
                ('parts_prize', models.FloatField()),
                ('work_prize', models.FloatField()),
                ('additional_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
