# Generated by Django 2.2.6 on 2019-11-13 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 14, 46, 6, 291707)),
        ),
        migrations.AddField(
            model_name='service',
            name='cli_desc',
            field=models.TextField(default='Brak opisu!'),
        ),
        migrations.AddField(
            model_name='service',
            name='cli_info',
            field=models.TextField(default='Brak info!'),
        ),
    ]
