# Generated by Django 2.2.6 on 2019-11-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0002_auto_20191113_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 16, 32, 55, 281217)),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='parts_prize',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_prize',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_prize',
            field=models.FloatField(default=0),
        ),
    ]
