# Generated by Django 2.2.6 on 2019-11-13 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0005_auto_20191113_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='partID',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='repairID',
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_name',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='serviceID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='warsztat.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 21, 16, 24, 310087)),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
    ]
