# Generated by Django 2.2.6 on 2019-11-16 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0007_auto_20191116_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='job_price',
            new_name='job_prize',
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 20, 40, 51, 571490)),
        ),
    ]
