# Generated by Django 2.2.6 on 2019-11-16 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0008_auto_20191116_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='version',
            field=models.TextField(default='x'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 22, 16, 4, 800355)),
        ),
    ]
