# Generated by Django 2.2.6 on 2019-11-17 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0010_auto_20191116_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='clientID',
            new_name='carID',
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 19, 20, 44, 554971)),
        ),
    ]
