# Generated by Django 2.2.6 on 2019-11-20 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat', '0012_auto_20191117_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.TextField(default='https://www.clipartwiki.com/iclipmax/wohRmi/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cli_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 15, 44, 53, 617390)),
        ),
    ]
